/**
 * Shopify scrape metrics sanity check.
 * Auto-generated by /shopify_scrape_metric — do not hand-edit REPORT.
 */
import { Divider, Grid, H1, H2, Stack, Stat, Table, Text } from "cursor/canvas";

const REPORT = {
  "sourceCsv": "shopify/out/mullingarpewter_shopify_unlisted.csv",
  "summary": {
    "totalRows": 756,
    "products": 147,
    "productRows": 147,
    "variants": 459,
    "variantRows": 312,
    "variantExtraRows": 312,
    "multiVariantProducts": 72,
    "singleVariantProducts": 75,
    "avgVariantsPerProduct": 3.12,
    "maxVariantsOnProduct": 30,
    "imageOnlyRows": 297,
    "categories": 44,
    "fieldsTracked": 51,
    "fieldsFullyPresent": 23,
    "fieldsWithMissing": 28,
    "fieldsWithPlaceholders": 3,
    "fieldsCompleteReal": 20,
    "unlistedProducts": 147,
    "publishedFalse": 147,
    "taxableFalse": 459
  },
  "variants": {
    "total": 459,
    "extraRows": 312,
    "multiVariantProducts": 72,
    "singleVariantProducts": 75,
    "avgPerProduct": 3.12,
    "maxOnProduct": 30,
    "topMultiVariant": [
      {
        "handle": "unisex-leather-like-wristband-with-irish-pewter-design",
        "variants": 30
      },
      {
        "handle": "gents-mechanical-pocket-watch-collection",
        "variants": 23
      },
      {
        "handle": "corkscrew-bottle-opener-collection",
        "variants": 14
      },
      {
        "handle": "stainless-steel-flask-with-pewter-design-collection",
        "variants": 14
      },
      {
        "handle": "glass-shot-glasses-with-pewter-embellishment",
        "variants": 13
      },
      {
        "handle": "irish-pewter-wine-stopper",
        "variants": 12
      },
      {
        "handle": "glass-beer-tankard-with-pewter-design",
        "variants": 11
      },
      {
        "handle": "irish-pewter-jewelry-boxes-mom-design-claddagh-or-plain",
        "variants": 9
      },
      {
        "handle": "money-clip-easter-rising-centenary",
        "variants": 8
      },
      {
        "handle": "drink-flask-with-pewter-embellishment",
        "variants": 7
      },
      {
        "handle": "traditional-christmas-decoration-collection",
        "variants": 7
      },
      {
        "handle": "classic-christmas-collection",
        "variants": 7
      },
      {
        "handle": "irish-christmas-collection",
        "variants": 7
      },
      {
        "handle": "pop-socket-phone-holders-worldwide-shipping-included",
        "variants": 7
      },
      {
        "handle": "ladies-pendant-watch-irish-designs",
        "variants": 6
      }
    ]
  },
  "categories": [
    {
      "category": "Drinkware",
      "products": 21,
      "pct": 14.3
    },
    {
      "category": "Gifts for Men",
      "products": 12,
      "pct": 8.2
    },
    {
      "category": "Gift",
      "products": 10,
      "pct": 6.8
    },
    {
      "category": "Tankard",
      "products": 9,
      "pct": 6.1
    },
    {
      "category": "Cross",
      "products": 9,
      "pct": 6.1
    },
    {
      "category": "CHESS SET",
      "products": 8,
      "pct": 5.4
    },
    {
      "category": "Religious",
      "products": 6,
      "pct": 4.1
    },
    {
      "category": "Homeware",
      "products": 5,
      "pct": 3.4
    },
    {
      "category": "Baby Gifts",
      "products": 5,
      "pct": 3.4
    },
    {
      "category": "Flask",
      "products": 5,
      "pct": 3.4
    },
    {
      "category": "GIFTS FOR HER",
      "products": 4,
      "pct": 2.7
    },
    {
      "category": "Measure",
      "products": 4,
      "pct": 2.7
    },
    {
      "category": "Jewellery",
      "products": 4,
      "pct": 2.7
    },
    {
      "category": "watch set",
      "products": 3,
      "pct": 2.0
    },
    {
      "category": "FLASK",
      "products": 3,
      "pct": 2.0
    },
    {
      "category": "Picture Frame",
      "products": 3,
      "pct": 2.0
    },
    {
      "category": "Christmas Tree Ornament",
      "products": 3,
      "pct": 2.0
    },
    {
      "category": "MEASURE",
      "products": 2,
      "pct": 1.4
    },
    {
      "category": "GOBLETS",
      "products": 2,
      "pct": 1.4
    },
    {
      "category": "Wine",
      "products": 2,
      "pct": 1.4
    },
    {
      "category": "gifts for her",
      "products": 2,
      "pct": 1.4
    },
    {
      "category": "cross",
      "products": 2,
      "pct": 1.4
    },
    {
      "category": "FRAME",
      "products": 2,
      "pct": 1.4
    },
    {
      "category": "Sculpture",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "CORK SCREW",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "MENS GIFTS",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "Watch",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "gift",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "TUMBLERS",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "ORNAMENT",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "CANDLE HOLDER",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "drinkware",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "Bookmarks",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "POP SOCKETS",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "BOOKMARK",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "letter openers",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "Gift Card",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "frames",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "Gifts for her",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "bookmarks",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "jewellery boxes",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "Sculptures",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "sports awards and trophies",
      "products": 1,
      "pct": 0.7
    },
    {
      "category": "Wedding",
      "products": 1,
      "pct": 0.7
    }
  ],
  "fields": [
    {
      "field": "Compare At Price / International",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Cost per item",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Age Group",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Condition",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Custom Label 0",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Custom Label 1",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Custom Label 2",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Custom Label 3",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Custom Label 4",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Custom Product",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Gender",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Google Product Category",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / MPN",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option3 Name",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option3 Value",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Price / International",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Product Category",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Barcode",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Compare At Price",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Image",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Tax Code",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option2 Name",
      "total": 459,
      "present": 2,
      "missing": 457,
      "real": 2,
      "placeholder": 0,
      "presentPct": 0.4,
      "missingPct": 99.6,
      "realPct": 0.4,
      "placeholderPct": 0.0
    },
    {
      "field": "Option2 Value",
      "total": 459,
      "present": 39,
      "missing": 420,
      "real": 39,
      "placeholder": 0,
      "presentPct": 8.5,
      "missingPct": 91.5,
      "realPct": 8.5,
      "placeholderPct": 0.0
    },
    {
      "field": "Option1 Name",
      "total": 459,
      "present": 147,
      "missing": 312,
      "real": 147,
      "placeholder": 0,
      "presentPct": 32.0,
      "missingPct": 68.0,
      "realPct": 32.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Image Alt Text",
      "total": 756,
      "present": 444,
      "missing": 312,
      "real": 444,
      "placeholder": 0,
      "presentPct": 58.7,
      "missingPct": 41.3,
      "realPct": 58.7,
      "placeholderPct": 0.0
    },
    {
      "field": "Image Position",
      "total": 756,
      "present": 444,
      "missing": 312,
      "real": 444,
      "placeholder": 0,
      "presentPct": 58.7,
      "missingPct": 41.3,
      "realPct": 58.7,
      "placeholderPct": 0.0
    },
    {
      "field": "Image Src",
      "total": 756,
      "present": 444,
      "missing": 312,
      "real": 444,
      "placeholder": 0,
      "presentPct": 58.7,
      "missingPct": 41.3,
      "realPct": 58.7,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant SKU",
      "total": 459,
      "present": 454,
      "missing": 5,
      "real": 454,
      "placeholder": 0,
      "presentPct": 98.9,
      "missingPct": 1.1,
      "realPct": 98.9,
      "placeholderPct": 0.0
    },
    {
      "field": "Body (HTML)",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Gift Card",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Handle",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Included / International",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Included / United States",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option1 Value",
      "total": 459,
      "present": 459,
      "missing": 0,
      "real": 459,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Published",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "SEO Description",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "SEO Title",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Status",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Tags",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Title",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Type",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Fulfillment Service",
      "total": 459,
      "present": 459,
      "missing": 0,
      "real": 459,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Grams",
      "total": 459,
      "present": 459,
      "missing": 0,
      "real": 39,
      "placeholder": 420,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 8.5,
      "placeholderPct": 91.5
    },
    {
      "field": "Variant Inventory Policy",
      "total": 459,
      "present": 459,
      "missing": 0,
      "real": 459,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Inventory Qty",
      "total": 459,
      "present": 459,
      "missing": 0,
      "real": 0,
      "placeholder": 459,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 0.0,
      "placeholderPct": 100.0
    },
    {
      "field": "Variant Inventory Tracker",
      "total": 459,
      "present": 459,
      "missing": 0,
      "real": 459,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Price",
      "total": 459,
      "present": 459,
      "missing": 0,
      "real": 451,
      "placeholder": 8,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 98.3,
      "placeholderPct": 1.7
    },
    {
      "field": "Variant Requires Shipping",
      "total": 459,
      "present": 459,
      "missing": 0,
      "real": 459,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Taxable",
      "total": 459,
      "present": 459,
      "missing": 0,
      "real": 459,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Weight Unit",
      "total": 459,
      "present": 459,
      "missing": 0,
      "real": 459,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Vendor",
      "total": 147,
      "present": 147,
      "missing": 0,
      "real": 147,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    }
  ],
  "topMissing": [
    {
      "field": "Compare At Price / International",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Cost per item",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Age Group",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Condition",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Custom Label 0",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Custom Label 1",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Custom Label 2",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Custom Label 3",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Custom Label 4",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Custom Product",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Gender",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / Google Product Category",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Google Shopping / MPN",
      "total": 147,
      "present": 0,
      "missing": 147,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option3 Name",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option3 Value",
      "total": 459,
      "present": 0,
      "missing": 459,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    }
  ],
  "statusCounts": {
    "unlisted": 147
  },
  "publishedCounts": {
    "false": 147
  },
  "taxableCounts": {
    "false": 459
  }
} as const;

export default function ShopifyScrapeMetrics() {
  const s = REPORT.summary;
  const fieldRows = REPORT.fields.map((f) => [
    f.field,
    String(f.present),
    String(f.missing),
    `${f.presentPct}%`,
    `${f.missingPct}%`,
    `${f.realPct}%`,
    `${f.placeholderPct}%`,
  ]);
  const categoryRows = REPORT.categories.map((c) => [
    c.category,
    String(c.products),
    `${c.pct}%`,
  ]);
  const missingRows = REPORT.topMissing.map((f) => [
    f.field,
    `${f.missingPct}%`,
    String(f.missing),
    String(f.present),
    `${f.placeholderPct}% placeholder`,
  ]);

  return (
    <Stack gap={20} style={{ padding: 20 }}>
      <H1>Shopify scrape metrics</H1>
      <Text tone="secondary">Source: {REPORT.sourceCsv}</Text>

      <Grid columns={4} gap={12}>
        <Stat value={String(s.products)} label="Products" />
        <Stat value={String(s.variants ?? s.variantRows)} label="Variants" />
        <Stat value={String(s.multiVariantProducts ?? 0)} label="Multi-variant products" />
        <Stat value={String(s.unlistedProducts)} label="Unlisted products" />
      </Grid>

      <Grid columns={4} gap={12}>
        <Stat value={String(s.categories)} label="Categories" />
        <Stat value={String(s.fieldsWithMissing)} label="Fields with missing" />
        <Stat value={String(s.avgVariantsPerProduct ?? 0)} label="Avg variants / product" />
        <Stat value={String(s.taxableFalse ?? 0)} label="Taxable=false rows" />
      </Grid>

      <Text>
        Rows {s.totalRows} · product {s.productRows} · variant extras {s.variantExtraRows ?? s.variantRows} ·
        image-only {s.imageOnlyRows} · Published=false {s.publishedFalse} · fields tracked {s.fieldsTracked} ·
        placeholder fields {s.fieldsWithPlaceholders}
      </Text>

      <Divider />
      <H2>Top multi-variant products</H2>
      <Table
        headers={["Handle", "Variants"]}
        rows={(REPORT.variants?.topMultiVariant ?? []).map((v) => [v.handle, String(v.variants)])}
      />

      <Divider />
      <H2>Categories</H2>
      <Table headers={["Category", "Products", "Share"]} rows={categoryRows} />

      <Divider />
      <H2>Top missing fields</H2>
      <Table
        headers={["Field", "Missing %", "Missing", "Present", "Note"]}
        rows={missingRows}
      />

      <Divider />
      <H2>All fields — present vs missing</H2>
      <Table
        headers={["Field", "Present", "Missing", "Present %", "Missing %", "Real %", "Placeholder %"]}
        rows={fieldRows}
      />
    </Stack>
  );
}
