/**
 * Shopify scrape metrics sanity check.
 * Auto-generated by /shopify_scrape_metric — do not hand-edit REPORT.
 */
import { Divider, Grid, H1, H2, Stack, Stat, Table, Text } from "cursor/canvas";

const REPORT = {
  "sourceCsv": "/workspace/shopify/out/keogh_shopify_unlisted.csv",
  "summary": {
    "totalRows": 2,
    "products": 2,
    "productRows": 2,
    "variantRows": 0,
    "imageOnlyRows": 0,
    "categories": 1,
    "fieldsTracked": 34,
    "fieldsFullyPresent": 26,
    "fieldsWithMissing": 8,
    "fieldsWithPlaceholders": 4,
    "fieldsCompleteReal": 22,
    "unlistedProducts": 2,
    "publishedFalse": 2
  },
  "categories": [
    {
      "category": "General",
      "products": 2,
      "pct": 100.0
    }
  ],
  "fields": [
    {
      "field": "Cost per item",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option2 Name",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option2 Value",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option3 Name",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option3 Value",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Product Category",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Barcode",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Compare At Price",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Body (HTML)",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Gift Card",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Handle",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Image Alt Text",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Image Position",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Image Src",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option1 Name",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option1 Value",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Published",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "SEO Description",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 0,
      "placeholder": 2,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 0.0,
      "placeholderPct": 100.0
    },
    {
      "field": "SEO Title",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Status",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Tags",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Title",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Type",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 0,
      "placeholder": 2,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 0.0,
      "placeholderPct": 100.0
    },
    {
      "field": "Variant Fulfillment Service",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Grams",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 0,
      "placeholder": 2,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 0.0,
      "placeholderPct": 100.0
    },
    {
      "field": "Variant Inventory Policy",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Inventory Qty",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 0,
      "placeholder": 2,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 0.0,
      "placeholderPct": 100.0
    },
    {
      "field": "Variant Inventory Tracker",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Price",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Requires Shipping",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant SKU",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Taxable",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Weight Unit",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Vendor",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    }
  ],
  "topMissing": [
    {
      "field": "Cost per item",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option2 Name",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option2 Value",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option3 Name",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option3 Value",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Product Category",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Barcode",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Variant Compare At Price",
      "total": 2,
      "present": 0,
      "missing": 2,
      "real": 0,
      "placeholder": 0,
      "presentPct": 0.0,
      "missingPct": 100.0,
      "realPct": 0.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Body (HTML)",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Gift Card",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Handle",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Image Alt Text",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Image Position",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Image Src",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    },
    {
      "field": "Option1 Name",
      "total": 2,
      "present": 2,
      "missing": 0,
      "real": 2,
      "placeholder": 0,
      "presentPct": 100.0,
      "missingPct": 0.0,
      "realPct": 100.0,
      "placeholderPct": 0.0
    }
  ],
  "statusCounts": {
    "unlisted": 2
  },
  "publishedCounts": {
    "false": 2
  }
} as const;

export default function ShopifyScrapeMetrics() {
  const s = REPORT.summary;
  const fieldRows = REPORT.fields.map((f) => [
    f.field,
    String(f.present),
    String(f.missing),
    `${f.presentPct}%`,
    `${f.missingPct}%`,
    `${f.realPct}%`,
    `${f.placeholderPct}%`,
  ]);
  const categoryRows = REPORT.categories.map((c) => [
    c.category,
    String(c.products),
    `${c.pct}%`,
  ]);
  const missingRows = REPORT.topMissing.map((f) => [
    f.field,
    `${f.missingPct}%`,
    String(f.missing),
    String(f.present),
    `${f.placeholderPct}% placeholder`,
  ]);

  return (
    <Stack gap={20} style={{ padding: 20 }}>
      <H1>Shopify scrape metrics</H1>
      <Text tone="secondary">Source: {REPORT.sourceCsv}</Text>

      <Grid columns={4} gap={12}>
        <Stat value={String(s.products)} label="Products" />
        <Stat value={String(s.categories)} label="Categories" />
        <Stat value={String(s.fieldsWithMissing)} label="Fields with missing" />
        <Stat value={String(s.unlistedProducts)} label="Unlisted products" />
      </Grid>

      <Text>
        Rows {s.totalRows} · product {s.productRows} · variant {s.variantRows} · image-only {s.imageOnlyRows} ·
        Published=false {s.publishedFalse} · fields tracked {s.fieldsTracked} ·
        placeholder fields {s.fieldsWithPlaceholders}
      </Text>

      <Divider />
      <H2>Categories</H2>
      <Table headers={["Category", "Products", "Share"]} rows={categoryRows} />

      <Divider />
      <H2>Top missing fields</H2>
      <Table
        headers={["Field", "Missing %", "Missing", "Present", "Note"]}
        rows={missingRows}
      />

      <Divider />
      <H2>All fields — present vs missing</H2>
      <Table
        headers={["Field", "Present", "Missing", "Present %", "Missing %", "Real %", "Placeholder %"]}
        rows={fieldRows}
      />
    </Stack>
  );
}
